window.GAME_QUESTIONS = [
  {
    question: "Countries That Start And End With A",
    prompt: "Name a country that starts and ends with A",
    startTeam: 1,
    answers: [
      { answer: "Andorra", score: 0 },
      { answer: "Antigua and Barbuda", score: 7, aliases: ["Antigua", "Barbuda"] },
      { answer: "Albania", score: 15 },
      { answer: "Algeria", score: 25 },
      { answer: "Angola", score: 35 },
      { answer: "Armenia", score: 50 },
      { answer: "Austria", score: 65 },
      { answer: "Argentina", score: 80 },
      { answer: "Australia", score: 90 }
    ]
  },
  {
    question: "Animals Beginning With C",
    prompt: "Name an animal beginning with the letter C",
    startTeam: 2,
    answers: [
      { answer: "Capybara", score: 0 },
      { answer: "Cassowary", score: 3 },
      { answer: "Caracal", score: 5 },
      { answer: "Coati", score: 7 },
      { answer: "Cuscus", score: 9 },
      { answer: "Civet", score: 11 },
      { answer: "Caiman", score: 13 },
      { answer: "Chinchilla", score: 15 },
      { answer: "Cormorant", score: 17 },
      { answer: "Crane", score: 20 },
      { answer: "Cockatoo", score: 22 },
      { answer: "Cuttlefish", score: 24 },
      { answer: "Centipede", score: 26 },
      { answer: "Clownfish", score: 28 },
      { answer: "Chipmunk", score: 32 },
      { answer: "Chimpanzee", score: 36, aliases: ["Chimp"] },
      { answer: "Canary", score: 40 },
      { answer: "Crow", score: 45 },
      { answer: "Cheetah", score: 52 },
      { answer: "Cougar", score: 56, aliases: ["Mountain Lion"] },
      { answer: "Coyote", score: 60 },
      { answer: "Cobra", score: 65 },
      { answer: "Camel", score: 70 },
      { answer: "Chicken", score: 78 },
      { answer: "Crab", score: 82 },
      { answer: "Crocodile", score: 86 },
      { answer: "Cow", score: 88 },
      { answer: "Cat", score: 90 }
    ]
  },
  {
    question: "Countries With A Mediterranean Coastline",
    prompt: "Name a country that has a coastline on the Mediterranean Sea",
    startTeam: 3,
    answers: [
      { answer: "Monaco", score: 0 },
      { answer: "Bosnia and Herzegovina", score: 4, aliases: ["Bosnia"] },
      { answer: "Slovenia", score: 8 },
      { answer: "Montenegro", score: 12 },
      { answer: "Malta", score: 16 },
      { answer: "Cyprus", score: 20 },
      { answer: "Albania", score: 24 },
      { answer: "Libya", score: 28 },
      { answer: "Tunisia", score: 32 },
      { answer: "Lebanon", score: 36 },
      { answer: "Croatia", score: 40 },
      { answer: "Syria", score: 45 },
      { answer: "Algeria", score: 50 },
      { answer: "Israel", score: 55 },
      { answer: "Morocco", score: 60 },
      { answer: "France", score: 65 },
      { answer: "Spain", score: 72 },
      { answer: "Egypt", score: 78 },
      { answer: "Turkey", score: 84 },
      { answer: "Greece", score: 88 },
      { answer: "Italy", score: 90 }
    ]
  },
  {
    question: "FIFA World Cup Finalists",
    prompt: "Name a country that has reached a FIFA World Cup Final",
    startTeam: 1,
    answers: [
      { answer: "Croatia", score: 0 },
      { answer: "Czechoslovakia", score: 5 },
      { answer: "Hungary", score: 10 },
      { answer: "Sweden", score: 15 },
      { answer: "Chile", score: 20 },
      { answer: "Netherlands", score: 28 },
      { answer: "Uruguay", score: 35 },
      { answer: "England", score: 45 },
      { answer: "Spain", score: 55 },
      { answer: "France", score: 65 },
      { answer: "Italy", score: 75 },
      { answer: "Argentina", score: 84 },
      { answer: "Germany", score: 88, aliases: ["West Germany"] },
      { answer: "Brazil", score: 90 }
    ]
  },
  {
    question: "Countries Shown In The Flags Picture",
    prompt: "Name one of the countries shown in the picture",
    startTeam: 2,
    image: "img/flags.jpg",
    answers: [
      { answer: "Gabon", score: 1 },
      { answer: "Suriname", score: 0 },
      { answer: "Botswana", score: 3 },
      { answer: "Andorra", score: 15 },
      { answer: "North Macedonia", score: 12, aliases: ["Macedonia"] },
      { answer: "Montenegro", score: 22 },
      { answer: "Malta", score: 27 },
      { answer: "Estonia", score: 35 },
      { answer: "Cyprus", score: 40 },
      { answer: "Albania", score: 42 },
      { answer: "Uruguay", score: 59 },
      { answer: "Croatia", score: 60 },
      { answer: "Belgium", score: 70 },
      { answer: "Austria", score: 63 },
      { answer: "Armenia", score: 90 }
    ]
  },
  {
    question: "Countries That Have Hosted The FIFA World Cup",
    prompt: "Name a country that has hosted a FIFA World Cup",
    startTeam: 3,
    answers: [
      { answer: "Switzerland", score: 0 },
      { answer: "Chile", score: 0 },
      { answer: "South Africa", score: 51 },
      { answer: "Uruguay", score: 15 },
      { answer: "Russia", score: 42 },
      { answer: "Qatar", score: 85 },
      { answer: "Sweden", score: 8 },
      { answer: "South Korea", score: 35, aliases: ["Korea Republic"] },
      { answer: "Japan", score: 40 },
      { answer: "Mexico", score: 45 },
      { answer: "Argentina", score: 50 },
      { answer: "England", score: 55 },
      { answer: "Spain", score: 60 },
      { answer: "France", score: 65 },
      { answer: "United States", score: 70, aliases: ["USA", "US", "United States of America"] },
      { answer: "Italy", score: 54 },
      { answer: "Germany", score: 76, aliases: ["West Germany"] },
      { answer: "Brazil", score: 72 }
    ]
  },
  {
    question: "Chemical Elements",
    prompt: "Name a chemical element from the periodic table",
    startTeam: 1,
    answers: [
      { answer: "Oganesson", score: 0 },
      { answer: "Livermorium", score: 2 },
      { answer: "Tennessine", score: 4 },
      { answer: "Moscovium", score: 6 },
      { answer: "Nihonium", score: 8 },
      { answer: "Copernicium", score: 10 },
      { answer: "Roentgenium", score: 12 },
      { answer: "Darmstadtium", score: 14 },
      { answer: "Meitnerium", score: 0 },
      { answer: "Hassium", score: 0 },
      { answer: "Bohrium", score: 20 },
      { answer: "Seaborgium", score: 22 },
      { answer: "Dubnium", score: 24 },
      { answer: "Rutherfordium", score: 26 },
      { answer: "Lawrencium", score: 28 },
      { answer: "Nobelium", score: 30 },
      { answer: "Mendelevium", score: 32 },
      { answer: "Fermium", score: 34 },
      { answer: "Einsteinium", score: 36 },
      { answer: "Californium", score: 38 },
      { answer: "Berkelium", score: 40 },
      { answer: "Curium", score: 42 },
      { answer: "Americium", score: 44 },
      { answer: "Plutonium", score: 46 },
      { answer: "Uranium", score: 50 },
      { answer: "Radium", score: 54 },
      { answer: "Radon", score: 58 },
      { answer: "Xenon", score: 62 },
      { answer: "Neon", score: 66 },
      { answer: "Helium", score: 70 },
      { answer: "Silver", score: 74 },
      { answer: "Tin", score: 76 },
      { answer: "Lead", score: 78 },
      { answer: "Zinc", score: 80 },
      { answer: "Nickel", score: 82 },
      { answer: "Aluminium", score: 84, aliases: ["Aluminum"] },
      { answer: "Copper", score: 86 },
      { answer: "Gold", score: 88 },
      { answer: "Iron", score: 89 }
    ]
  },
  {
    question: "Provinces Of Armenia",
    prompt: "Name a province (Մարզ) of Armenia",
    startTeam: 3,
    answers: [
      { answer: "Aragatsotn", score: 6, aliases: ["aragadzodn", "aragatzotn"] },
      { answer: "Kotayk", score: 11, aliases: ["godayk", "kotayq"] },
      { answer: "Armavir", score: 16 },
      { answer: "Gegharkunik", score: 22, aliases: ["kegharkunik", "gegharqunik", "kegharkounik"] },
      { answer: "Vayots Dzor", score: 28, aliases: ["vayots tsor", "vayotsdzor", "vayotstsor"] },
      { answer: "Shirak", score: 34, aliases: ["shirag"] },
      { answer: "Tavush", score: 41, aliases: ["davush", "davoush", "tavoush"] },
      { answer: "Lori", score: 47 },
      { answer: "Syunik", score: 55, aliases: ["sunik", "siunik", "sounik", "sjunik"] },
      { answer: "Ararat", score: 72, aliases: ["ararad"] },
      { answer: "Yerevan", score: 93, aliases: ["erevan", "yerevani"] }
    ]
  },
  {
    question: "Disney And Pixar Animated Films Released Since 2000",
    prompt: "Name a Disney or Pixar animated film released since 2000",
    startTeam: 1,
    answers: [
      { answer: "The Good Dinosaur", score: 0 },
      { answer: "Onward", score: 2 },
      { answer: "Elemental", score: 4 },
      { answer: "Luca", score: 6 },
      { answer: "Turning Red", score: 8 },
      { answer: "Soul", score: 10 },
      { answer: "Lightyear", score: 12 },
      { answer: "Brave", score: 14 },
      { answer: "Cars 2", score: 16 },
      { answer: "Cars 3", score: 18 },
      { answer: "Finding Dory", score: 20 },
      { answer: "Monsters University", score: 22 },
      { answer: "Incredibles 2", score: 24 },
      { answer: "Toy Story 4", score: 26 },
      { answer: "A Bug's Life 2", score: 28 },
      { answer: "Home on the Range", score: 30 },
      { answer: "Treasure Planet", score: 32 },
      { answer: "Meet the Robinsons", score: 34 },
      { answer: "Chicken Little", score: 36 },
      { answer: "Bolt", score: 38 },
      { answer: "Atlantis: The Lost Empire", score: 40, aliases: ["atlantis"] },
      { answer: "Brother Bear", score: 42 },
      { answer: "Dinosaur", score: 44 },
      { answer: "Strange World", score: 46 },
      { answer: "Wish", score: 48 },
      { answer: "Raya and the Last Dragon", score: 50, aliases: ["raya"] },
      { answer: "The Princess and the Frog", score: 52 },
      { answer: "Big Hero 6", score: 55 },
      { answer: "Wreck-It Ralph", score: 58, aliases: ["wreck it ralph"] },
      { answer: "Ralph Breaks the Internet", score: 60 },
      { answer: "Lilo & Stitch", score: 62, aliases: ["lilo and stitch"] },
      { answer: "Encanto", score: 65 },
      { answer: "Tangled", score: 68 },
      { answer: "Moana", score: 72 },
      { answer: "Frozen 2", score: 76 },
      { answer: "Frozen", score: 80 },
      { answer: "Cars", score: 82 },
      { answer: "Finding Nemo", score: 84 },
      { answer: "Monsters, Inc.", score: 86, aliases: ["monsters inc"] },
      { answer: "Up", score: 88 },
      { answer: "The Incredibles", score: 89, aliases: ["incredibles"] },
      { answer: "Toy Story 3", score: 90 }
    ]
  },
  {
    question: "Countries Using The Euro",
    prompt: "Name a country that uses the Euro as its official currency",
    startTeam: 2,
    answers: [
      { answer: "San Marino", score: 0 },
      { answer: "Andorra", score: 2 },
      { answer: "Monaco", score: 0 },
      { answer: "Vatican City", score: 4, aliases: ["vatican"] },
      { answer: "Malta", score: 12 },
      { answer: "Cyprus", score: 25 },
      { answer: "Slovenia", score: 30 },
      { answer: "Slovakia", score: 24 },
      { answer: "Estonia", score: 33 },
      { answer: "Latvia", score: 21 },
      { answer: "Lithuania", score: 39 },
      { answer: "Luxembourg", score: 33 },
      { answer: "Ireland", score: 53 },
      { answer: "Austria", score: 62 },
      { answer: "Belgium", score: 77 },
      { answer: "Portugal", score: 75 },
      { answer: "Netherlands", score: 80 },
      { answer: "Greece", score: 84 },
      { answer: "Spain", score: 87 },
      { answer: "Italy", score: 88 },
      { answer: "France", score: 89 },
      { answer: "Germany", score: 90 }
    ]
  },
  {
    question: "Political Parties And Alliances In The 2026 Armenian Parliamentary Election",
    prompt: "Name a party or alliance that participated in the 2026 parliamentary election",
    startTeam: 2,
    answers: [
      { answer: "Kochari National Revival and National Awakening Party", score: 1, aliases: ["kochari", "kochari party"] },
      { answer: "Meritocratic Party of Armenia", score: 3, aliases: ["meritocratic party", "meritocratic"] },
      { answer: "Reformists Party", score: 5, aliases: ["reformist party", "reformists"] },
      { answer: "Christian Democratic Party", score: 9, aliases: ["christian democrats"] },
      { answer: "Democracy Law Discipline Party", score: 11, aliases: ["dok", "dlo", "democracy law order"] },
      { answer: "Wings of Unity Party", score: 14, aliases: ["wings of unity"] },
      { answer: "Democratic Consolidation Party", score: 17, aliases: ["democratic consolidation"] },
      { answer: "\"Against All\" Democratic Party", score: 22, aliases: ["against all", "against everyone", "polorin dem em"] },
      { answer: "National Democratic Alliance", score: 26, aliases: ["nda", "national democratic pole"] },
      { answer: "For The Republic Party", score: 31, aliases: ["for the republic"] },
      { answer: "New Power", score: 38, aliases: ["new force", "new power party"] },
      { answer: "Armenian National Congress", score: 44, aliases: ["anc", "ter-petrosyan party"] },
      { answer: "Bright Armenia", score: 51, aliases: ["lusavor hayastan"] },
      { answer: "Hanrapetutyun Party", score: 57, aliases: ["republic party", "hanrapetutyun", "aram sargsyan party"] },
      { answer: "Prosperous Armenia", score: 64, aliases: ["bhk", "bargavach hayastan", "tsarukyan"] },
      { answer: "Strong Armenia Alliance", score: 71, aliases: ["strong armenia", "karapetyan alliance"] },
      { answer: "Armenia Alliance", score: 79, aliases: ["hayastan alliance", "kocharyan alliance"] },
      { answer: "Civil Contract", score: 88, aliases: ["qp", "civic contract", "pashinyan party"] }
    ]
  },
  {
    question: "Countries That Have Won Eurovision",
    prompt: "Name a country that has won the Eurovision Song Contest",
    startTeam: 2,
    answers: [
      { answer: "Yugoslavia", score: 0 },
      { answer: "Monaco", score: 2 },
      { answer: "Luxembourg", score: 4 },
      { answer: "Latvia", score: 5 },
      { answer: "Estonia", score: 7 },
      { answer: "Belgium", score: 9 },
      { answer: "Serbia", score: 12 },
      { answer: "Portugal", score: 16 },
      { answer: "Turkey", score: 18, aliases: ["türkiye"] },
      { answer: "Azerbaijan", score: 21 },
      { answer: "Austria", score: 24 },
      { answer: "Finland", score: 28 },
      { answer: "Switzerland", score: 33 },
      { answer: "Denmark", score: 37 },
      { answer: "Russia", score: 42 },
      { answer: "Netherlands", score: 46, aliases: ["holland", "the netherlands"] },
      { answer: "Germany", score: 50 },
      { answer: "Israel", score: 54 },
      { answer: "Norway", score: 57 },
      { answer: "Bulgaria", score: 60 },
      { answer: "Spain", score: 63 },
      { answer: "Greece", score: 66 },
      { answer: "France", score: 70 },
      { answer: "Italy", score: 73 },
      { answer: "Ukraine", score: 77 },
      { answer: "United Kingdom", score: 81, aliases: ["uk", "britain", "great britain", "england"] },
      { answer: "Ireland", score: 88 },
      { answer: "Sweden", score: 94 }
    ]
  },
  {
    question: "Most Famous Kings Of Armenia Throughout History",
    prompt: "Name a king of Armenia",
    startTeam: 3,
    answers: [
      { answer: "Tiran", score: 2, aliases: ["diran", "tigranes vii"] },
      { answer: "Varazdat", score: 3, aliases: ["varaztad"] },
      { answer: "Levon V", score: 4, aliases: ["levon e", "leon v", "levon v of cilicia"] },
      { answer: "Smbat I", score: 6, aliases: ["smbat a", "smpad", "smbat the martyr"] },
      { answer: "Khosrov III", score: 8, aliases: ["khosrov kotak", "khosrov g", "khosrof", "khosrov the small"] },
      { answer: "Artavasdes II", score: 10, aliases: ["artavazd ii", "artavazd b", "ardavazt"] },
      { answer: "Gagik II", score: 12, aliases: ["gagik b", "kakig b"] },
      { answer: "Vramshapuh", score: 14, aliases: ["vramshabouh", "vramshapouh"] },
      { answer: "Arshak II", score: 16, aliases: ["arshak b", "arshag", "arsaces ii"] },
      { answer: "Ashot III", score: 19, aliases: ["ashot g", "ashod", "ashot voghormats", "ashot the merciful"] },
      { answer: "Gagik I", score: 22, aliases: ["gagik a", "kakig", "gagik bagratuni"] },
      { answer: "Pap", score: 25, aliases: ["bab", "papas"] },
      { answer: "Levon I", score: 28, aliases: ["levon a", "leon i", "levon i of cilicia"] },
      { answer: "Hetoum I", score: 32, aliases: ["hetoum a", "hethum i", "hetum i", "hetoum the first"] },
      { answer: "Tiridates I", score: 35, aliases: ["trdat a", "trdat i", "drtad a"] },
      { answer: "Levon II", score: 43, aliases: ["levon b", "levon mets", "levon the magnificent", "leon ii"] },
      { answer: "Artashes I", score: 51, aliases: ["artashes a", "ardashes", "artaxias i", "artashes hayrenaser"] },
      { answer: "Ashot I", score: 59, aliases: ["ashot a", "ashod", "ashot mets", "ashot the great", "ashot bagratuni"] },
      { answer: "Trdat III", score: 74, aliases: ["trdat", "drtad", "trdat g", "trdat mets", "trdat the great", "tiridates iii", "tiridates the great"] },
      { answer: "Tigranes II", score: 93, aliases: ["tigran", "tigran b", "tigran mets", "tigran the great", "tigranes the great"] }
    ]
  }
];