window.GAME_QUESTIONS = [
  {
    question: "Countries That Start And End With A",
    prompt: "Name a country that starts and ends with A",
    startTeam: 1,
    answers: [
      { answer: "Andorra", score: 0 },
      { answer: "Antigua and Barbuda", score: 7, aliases: ["Antigua", "Barbuda"] },
      { answer: "Albania", score: 15 },
      { answer: "Algeria", score: 25 },
      { answer: "Angola", score: 35 },
      { answer: "Armenia", score: 50 },
      { answer: "Austria", score: 65 },
      { answer: "Argentina", score: 80 },
      { answer: "Australia", score: 90 }
    ]
  },
  {
    question: "Animals Beginning With C",
    prompt: "Name an animal beginning with the letter C",
    startTeam: 2,
    answers: [
      { answer: "Capybara", score: 0 },
      { answer: "Cassowary", score: 3 },
      { answer: "Caracal", score: 5 },
      { answer: "Coati", score: 7 },
      { answer: "Cuscus", score: 9 },
      { answer: "Civet", score: 11 },
      { answer: "Caiman", score: 13 },
      { answer: "Chinchilla", score: 15 },
      { answer: "Cormorant", score: 17 },
      { answer: "Crane", score: 20 },
      { answer: "Cockatoo", score: 22 },
      { answer: "Cuttlefish", score: 24 },
      { answer: "Centipede", score: 26 },
      { answer: "Clownfish", score: 28 },
      { answer: "Chipmunk", score: 32 },
      { answer: "Chimpanzee", score: 36, aliases: ["Chimp"] },
      { answer: "Canary", score: 40 },
      { answer: "Crow", score: 45 },
      { answer: "Cheetah", score: 52 },
      { answer: "Cougar", score: 56, aliases: ["Mountain Lion"] },
      { answer: "Coyote", score: 60 },
      { answer: "Cobra", score: 65 },
      { answer: "Camel", score: 70 },
      { answer: "Chicken", score: 78 },
      { answer: "Crab", score: 82 },
      { answer: "Crocodile", score: 86 },
      { answer: "Cow", score: 88 },
      { answer: "Cat", score: 90 }
    ]
  },
  {
    question: "Countries With A Mediterranean Coastline",
    prompt: "Name a country that has a coastline on the Mediterranean Sea",
    startTeam: 3,
    answers: [
      { answer: "Monaco", score: 0 },
      { answer: "Bosnia and Herzegovina", score: 4, aliases: ["Bosnia"] },
      { answer: "Slovenia", score: 8 },
      { answer: "Montenegro", score: 12 },
      { answer: "Malta", score: 16 },
      { answer: "Cyprus", score: 20 },
      { answer: "Albania", score: 24 },
      { answer: "Libya", score: 28 },
      { answer: "Tunisia", score: 32 },
      { answer: "Lebanon", score: 36 },
      { answer: "Croatia", score: 40 },
      { answer: "Syria", score: 45 },
      { answer: "Algeria", score: 50 },
      { answer: "Israel", score: 55 },
      { answer: "Morocco", score: 60 },
      { answer: "France", score: 65 },
      { answer: "Spain", score: 72 },
      { answer: "Egypt", score: 78 },
      { answer: "Turkey", score: 84 },
      { answer: "Greece", score: 88 },
      { answer: "Italy", score: 90 }
    ]
  },
  {
    question: "FIFA World Cup Finalists",
    prompt: "Name a country that has reached a FIFA World Cup Final",
    startTeam: 1,
    answers: [
      { answer: "Croatia", score: 0 },
      { answer: "Czechoslovakia", score: 5 },
      { answer: "Hungary", score: 10 },
      { answer: "Sweden", score: 15 },
      { answer: "Chile", score: 20 },
      { answer: "Netherlands", score: 28 },
      { answer: "Uruguay", score: 35 },
      { answer: "England", score: 45 },
      { answer: "Spain", score: 55 },
      { answer: "France", score: 65 },
      { answer: "Italy", score: 75 },
      { answer: "Argentina", score: 84 },
      { answer: "Germany", score: 88, aliases: ["West Germany"] },
      { answer: "Brazil", score: 90 }
    ]
  },
  {
    question: "Countries Shown In The Flags Picture",
    prompt: "Name one of the countries shown in the picture",
    startTeam: 2,
    image: "img/flags.jpg",
    answers: [
      { answer: "Gabon", score: 1 },
      { answer: "Suriname", score: 0 },
      { answer: "Botswana", score: 3 },
      { answer: "Andorra", score: 15 },
      { answer: "North Macedonia", score: 12, aliases: ["Macedonia"] },
      { answer: "Montenegro", score: 22 },
      { answer: "Malta", score: 27 },
      { answer: "Estonia", score: 35 },
      { answer: "Cyprus", score: 40 },
      { answer: "Albania", score: 42 },
      { answer: "Uruguay", score: 59 },
      { answer: "Croatia", score: 60 },
      { answer: "Belgium", score: 70 },
      { answer: "Austria", score: 63 },
      { answer: "Armenia", score: 90 }
    ]
  },
  {
    question: "Countries That Have Hosted The FIFA World Cup",
    prompt: "Name a country that has hosted a FIFA World Cup",
    startTeam: 3,
    answers: [
      { answer: "Switzerland", score: 0 },
      { answer: "Chile", score: 0 },
      { answer: "South Africa", score: 51 },
      { answer: "Uruguay", score: 15 },
      { answer: "Russia", score: 42 },
      { answer: "Qatar", score: 85 },
      { answer: "Sweden", score: 8 },
      { answer: "South Korea", score: 35, aliases: ["Korea Republic"] },
      { answer: "Japan", score: 40 },
      { answer: "Mexico", score: 45 },
      { answer: "Argentina", score: 50 },
      { answer: "England", score: 55 },
      { answer: "Spain", score: 60 },
      { answer: "France", score: 65 },
      { answer: "United States", score: 70, aliases: ["USA", "US", "United States of America"] },
      { answer: "Italy", score: 54 },
      { answer: "Germany", score: 76, aliases: ["West Germany"] },
      { answer: "Brazil", score: 72 }
    ]
  },
  {
    question: "Chemical Elements",
    prompt: "Name a chemical element from the periodic table",
    startTeam: 1,
    answers: [
      { answer: "Oganesson", score: 0 },
      { answer: "Livermorium", score: 2 },
      { answer: "Tennessine", score: 4 },
      { answer: "Moscovium", score: 6 },
      { answer: "Nihonium", score: 8 },
      { answer: "Copernicium", score: 10 },
      { answer: "Roentgenium", score: 12 },
      { answer: "Darmstadtium", score: 14 },
      { answer: "Meitnerium", score: 0 },
      { answer: "Hassium", score: 0 },
      { answer: "Bohrium", score: 20 },
      { answer: "Seaborgium", score: 22 },
      { answer: "Dubnium", score: 24 },
      { answer: "Rutherfordium", score: 26 },
      { answer: "Lawrencium", score: 28 },
      { answer: "Nobelium", score: 30 },
      { answer: "Mendelevium", score: 32 },
      { answer: "Fermium", score: 34 },
      { answer: "Einsteinium", score: 36 },
      { answer: "Californium", score: 38 },
      { answer: "Berkelium", score: 40 },
      { answer: "Curium", score: 42 },
      { answer: "Americium", score: 44 },
      { answer: "Plutonium", score: 46 },
      { answer: "Uranium", score: 50 },
      { answer: "Radium", score: 54 },
      { answer: "Radon", score: 58 },
      { answer: "Xenon", score: 62 },
      { answer: "Neon", score: 66 },
      { answer: "Helium", score: 70 },
      { answer: "Silver", score: 74 },
      { answer: "Tin", score: 76 },
      { answer: "Lead", score: 78 },
      { answer: "Zinc", score: 80 },
      { answer: "Nickel", score: 82 },
      { answer: "Aluminium", score: 84, aliases: ["Aluminum"] },
      { answer: "Copper", score: 86 },
      { answer: "Gold", score: 88 },
      { answer: "Iron", score: 89 }
    ]
  }
];